# Current version: 1.8.1

gaps:
  inner_gap: 1
  outer_gap: 1

bar:
  height: 30
  position: "top"
  opacity: 0.9
  background: "#101010"
  foreground: "white"
  font_family: "IBM Plex Mono"
  font_size: "13"
  padding: "1 6 1 6"
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#8192B3"
      displayed_workspace_background: "#42403e"
      default_workspace_background: "#101010"
  components_right:
    - type: "clock"
      time_formatting: "dd MMM yyyy hh:mm tt "

workspaces:
  - name: 6
    display_name: "Second Monitor"
    bind_to_monitor: 1
  - name: 1
    display_name: "Browser"
  - name: 2
    display_name: "APP"
  - name: 3
    display_name: "API"
  - name: 4
  - name: 5
  - name: 7
  - name: 8
  - name: 9

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  #- command: "ignore"
  #  match_process_name: "Taskmgr"

  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  - command: "set floating"
    match_class_name: "#32770"

  # Some applications (eg. Steam) have borders that extend past the normal border size.
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

  - command: "ignore"
    match_process_name: "wezterm-gui"

  - command: "ignore"
    match_process_name: "openconsole"

  - command: "ignore"
    match_process_name: "pwsh"

  - command: "ignore"
    match_process_name: "wezterm"

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["F24+H", "F24+Left"]
  - command: "focus right"
    bindings: ["F24+L", "F24+Right"]
  - command: "focus up"
    bindings: ["F24+K", "F24+Up"]
  - command: "focus down"
    bindings: ["F24+J", "F24+Down"]

  # Move focused window in a given direction.
  - command: "move left"
    bindings: ["F24+Control+H", "F24+Control+Left"]
  - command: "move right"
    bindings: ["F24+Control+L", "F24+Control+Right"]
  - command: "move up"
    bindings: ["F24+Control+K", "F24+Control+Up"]
  - command: "move down"
    bindings: ["F24+Control+J", "F24+Control+Down"]

  # Resize focused window by a percentage or pixel amount.
  - command: "resize width -2%"
    binding: "F24+Y"
  - command: "resize width +2%"
    binding: "F24+U"
  - command: "resize height +2%"
    binding: "F24+I"
  - command: "resize height -2%"
    binding: "F24+P"

  # Change layout direction to be either horizontal or vertical.
  - command: "layout horizontal"
    binding: "F24+Control+V"
  - command: "layout vertical"
    binding: "F24+V" 

  # Change focus between floating / tiling windows.
  - command: "toggle focus mode"
    binding: "F24+Control+Space"

  # Change the focused window to be floating / tiling.
  - command: "toggle floating"
    binding: "F24+Control+F"

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "F24+X"

  # Minimize focused window.
  - command: "set minimized"
    binding: "F24+M"

  # Close focused window.
  - command: "close"
    binding: "F24+Q"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "F24+Control+Q"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "F24+Control+Z"

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  # - command: "exec wezterm"
  # binding: "F24+T"

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace next"
    binding: "F24+D"
  - command: "focus workspace prev"
    binding: "F24+Shift+D"
  - command: "focus workspace 1"
    binding: "F24+W"
  - command: "focus workspace 2"
    binding: "F24+E"
  - command: "focus workspace 3"
    binding: "F24+R"
  - command: "focus workspace 4"
    binding: "F24+1"
  - command: "focus workspace 5"
    binding: "F24+2"
  - command: "focus workspace 6"
    binding: "F24+3"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "F24+Control+W"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "F24+Control+E"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "F24+Control+R"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "F24+Control+1"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "F24+Control+2"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "F24+Control+3"